import { lightColors } from './colors';
import { typography } from './typography';
import { spacing } from './spacing';
import { breakpoints } from './breakpoints';
import { effects } from './effects';
import { semanticTokens } from './semantic';
import { animations } from './animations';
import { elevation } from './elevation';
import { radius } from './radius';

export type ColorToken = keyof typeof lightColors;
export type TypographyToken = keyof typeof typography;
export type SpacingToken = keyof typeof spacing;
export type BreakpointToken = keyof typeof breakpoints;
export type EffectToken = keyof typeof effects;
export type SemanticToken = keyof typeof semanticTokens;
export type AnimationToken = keyof typeof animations;
export type AnimationPreset = keyof typeof animations.presets;
export type ElevationToken = keyof typeof elevation;
export type ElevationPreset = keyof typeof elevation.presets;
export type RadiusToken = keyof typeof radius;
export type RadiusPreset = keyof typeof radius.presets; 